In [ ]:
# Check if a GPU is available
!nvidia-smi || echo 'No GPU available. You may be on a CPU-only runtime.'

Tue Dec 23 07:23:30 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   42C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%%bash
curl -fsSL https://ollama.com/install.sh | sh

WARNING: systemd is not running
WARNING: Unable to detect NVIDIA/AMD GPU. Install lspci or lshw to automatically detect and install GPU dependencies.

>>> Cleaning up old version at /usr/local/lib/ollama
>>> Installing ollama to /usr/local
>>> Downloading Linux amd64 bundle
######################################################################## 100.0%
>>> Creating ollama user...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.

In [ ]:
# Create a persistent models directory in Google Drive
!mkdir -p /content/drive/MyDrive/RAG/ollama_models

# Remove any existing ephemeral models directory
!rm -rf ~/.ollama/models

# Symlink Ollama's model directory to Google Drive
!ln -s /content/drive/MyDrive/RAG/ollama_models ~/.ollama/models

print('Symlinked ~/.ollama/models -> /content/drive/MyDrive/RAG/ollama_models')

ln: failed to create symbolic link '/root/.ollama/models': No such file or directory
Symlinked ~/.ollama/models -> /content/drive/MyDrive/RAG/ollama_models

In [ ]:
import subprocess, time

server = subprocess.Popen(['ollama', 'serve'])
print('Ollama server started as background process (PID:', server.pid, ')')
time.sleep(5)
print('Waited 5 seconds for the server to initialize.')

Ollama server started as background process (PID: 2343 )
Waited 5 seconds for the server to initialize.

In [ ]:
# LLM
!ollama pull gemma3:4b

# SLM
!ollama pull gemma3:1b

In [ ]:
!pip install -r '/content/drive/MyDrive/RAG/requirements.txt'

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/RAG/requirements.txt (line 1)) (1.2.0)
Collecting langchain-community (from -r /content/drive/MyDrive/RAG/requirements.txt (line 2))
  Downloading langchain_community-0.4.1-py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-ollama (from -r /content/drive/MyDrive/RAG/requirements.txt (line 3))
  Downloading langchain_ollama-1.0.1-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: langgraph in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/RAG/requirements.txt (line 4)) (1.0.5)
Collecting faiss-cpu (from -r /content/drive/MyDrive/RAG/requirements.txt (line 5))
  Downloading faiss_cpu-1.13.1-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.6 kB)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/RAG/requirements.txt (line 6)) (2.12.3)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/RAG/requirements.txt (line 7)) (1.2.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/RAG/requirements.txt (line 8)) (4.13.5)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/RAG/requirements.txt (line 9)) (2.32.4)
Collecting streamlit (from -r /content/drive/MyDrive/RAG/requirements.txt (line 10))
  Downloading streamlit-1.52.2-py3-none-any.whl.metadata (9.8 kB)
Collecting wikipedia (from -r /content/drive/MyDrive/RAG/requirements.txt (line 11))
  Downloading wikipedia-1.4.0.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
Collecting pypdf (from -r /content/drive/MyDrive/RAG/requirements.txt (line 12))
  Downloading pypdf-6.5.0-py3-none-any.whl.metadata (7.1 kB)
Collecting langchain_chroma (from -r /content/drive/MyDrive/RAG/requirements.txt (line 13))
  Downloading langchain_chroma-1.1.0-py3-none-any.whl.metadata (1.9 kB)
Collecting langchain-huggingface (from -r /content/drive/MyDrive/RAG/requirements.txt (line 15))
  Downloading langchain_huggingface-1.2.0-py3-none-any.whl.metadata (2.8 kB)
Collecting langchain-experimental (from -r /content/drive/MyDrive/RAG/requirements.txt (line 17))
  Downloading langchain_experimental-0.4.1-py3-none-any.whl.metadata (1.3 kB)
Collecting rank_bm25 (from -r /content/drive/MyDrive/RAG/requirements.txt (line 19))
  Downloading rank_bm25-0.2.2-py3-none-any.whl.metadata (3.2 kB)
Collecting flashrank (from -r /content/drive/MyDrive/RAG/requirements.txt (line 21))
  Downloading FlashRank-0.2.10-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from langchain->-r /content/drive/MyDrive/RAG/requirements.txt (line 1)) (1.2.1)
Collecting langchain-classic<2.0.0,>=1.0.0 (from langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2))
  Downloading langchain_classic-1.0.0-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2)) (2.0.45)
Collecting requests (from -r /content/drive/MyDrive/RAG/requirements.txt (line 9))
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2)) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2)) (3.13.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2)) (9.1.2)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2))
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2)) (2.12.0)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2)) (0.4.59)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2)) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2)) (2.0.2)
Collecting ollama<1.0.0,>=0.6.0 (from langchain-ollama->-r /content/drive/MyDrive/RAG/requirements.txt (line 3))
  Downloading ollama-0.6.1-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph->-r /content/drive/MyDrive/RAG/requirements.txt (line 4)) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langgraph->-r /content/drive/MyDrive/RAG/requirements.txt (line 4)) (1.0.5)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph->-r /content/drive/MyDrive/RAG/requirements.txt (line 4)) (0.3.0)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph->-r /content/drive/MyDrive/RAG/requirements.txt (line 4)) (3.6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu->-r /content/drive/MyDrive/RAG/requirements.txt (line 5)) (25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->-r /content/drive/MyDrive/RAG/requirements.txt (line 6)) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->-r /content/drive/MyDrive/RAG/requirements.txt (line 6)) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic->-r /content/drive/MyDrive/RAG/requirements.txt (line 6)) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->-r /content/drive/MyDrive/RAG/requirements.txt (line 6)) (0.4.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->-r /content/drive/MyDrive/RAG/requirements.txt (line 8)) (2.8)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->-r /content/drive/MyDrive/RAG/requirements.txt (line 9)) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->-r /content/drive/MyDrive/RAG/requirements.txt (line 9)) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->-r /content/drive/MyDrive/RAG/requirements.txt (line 9)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->-r /content/drive/MyDrive/RAG/requirements.txt (line 9)) (2025.11.12)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/RAG/requirements.txt (line 10)) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/RAG/requirements.txt (line 10)) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/RAG/requirements.txt (line 10)) (6.2.4)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/RAG/requirements.txt (line 10)) (8.3.1)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/RAG/requirements.txt (line 10)) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/RAG/requirements.txt (line 10)) (11.3.0)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/RAG/requirements.txt (line 10)) (5.29.5)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/RAG/requirements.txt (line 10)) (18.1.0)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/RAG/requirements.txt (line 10)) (0.10.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/RAG/requirements.txt (line 10)) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/RAG/requirements.txt (line 10)) (3.1.45)
Collecting pydeck<1,>=0.8.0b4 (from streamlit->-r /content/drive/MyDrive/RAG/requirements.txt (line 10))
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit->-r /content/drive/MyDrive/RAG/requirements.txt (line 10)) (6.5.1)
Collecting chromadb<2.0.0,>=1.3.5 (from langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13))
  Downloading chromadb-1.3.7-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.2 kB)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.33.4 in /usr/local/lib/python3.12/dist-packages (from langchain-huggingface->-r /content/drive/MyDrive/RAG/requirements.txt (line 15)) (0.36.0)
Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from langchain-huggingface->-r /content/drive/MyDrive/RAG/requirements.txt (line 15)) (0.22.1)
Collecting onnxruntime (from flashrank->-r /content/drive/MyDrive/RAG/requirements.txt (line 21))
  Downloading onnxruntime-1.23.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.1 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from flashrank->-r /content/drive/MyDrive/RAG/requirements.txt (line 21)) (4.67.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2)) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2)) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2)) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2)) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2)) (1.22.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r /content/drive/MyDrive/RAG/requirements.txt (line 10)) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r /content/drive/MyDrive/RAG/requirements.txt (line 10)) (4.25.1)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit->-r /content/drive/MyDrive/RAG/requirements.txt (line 10)) (2.13.0)
Collecting build>=1.0.3 (from chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13))
  Downloading build-1.3.0-py3-none-any.whl.metadata (5.6 kB)
Collecting pybase64>=1.4.1 (from chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13))
  Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (8.7 kB)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13)) (0.38.0)
Collecting posthog<6.0.0,>=2.4.0 (from chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13))
  Downloading posthog-5.4.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13)) (1.37.0)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13))
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.39.1-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13)) (1.37.0)
Collecting pypika>=0.48.9 (from chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13))
  Downloading PyPika-0.48.9.tar.gz (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 4.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13)) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13)) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13)) (1.76.0)
Collecting bcrypt>=4.0.1 (from chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13))
  Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (10 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13)) (0.20.0)
Collecting kubernetes>=28.1.0 (from chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13))
  Downloading kubernetes-34.1.0-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13)) (5.2.0)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13)) (3.11.5)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13)) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma->-r /content/drive/MyDrive/RAG/requirements.txt (line 13)) (13.9.4)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2))
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2))
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit->-r /content/drive/MyDrive/RAG/requirements.txt (line 10)) (4.0.12)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain-huggingface->-r /content/drive/MyDrive/RAG/requirements.txt (line 15)) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain-huggingface->-r /content/drive/MyDrive/RAG/requirements.txt (line 15)) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain-huggingface->-r /content/drive/MyDrive/RAG/requirements.txt (line 15)) (1.2.0)
Collecting langchain-text-splitters<2.0.0,>=1.0.0 (from langchain-classic<2.0.0,>=1.0.0->langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2))
  Downloading langchain_text_splitters-1.1.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain->-r /content/drive/MyDrive/RAG/requirements.txt (line 1)) (1.33)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain->-r /content/drive/MyDrive/RAG/requirements.txt (line 1)) (0.12.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph->-r /content/drive/MyDrive/RAG/requirements.txt (line 4)) (1.12.1)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2)) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community->-r /content/drive/MyDrive/RAG/requirements.txt (line 2)) (0.25.0)
Collecting coloredlogs (from onnxruntime->flashrank->-r /content/drive/MyDrive/RAG/requirements.txt (line 21))
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)

In [ ]:
from pathlib import Path
import sys
import time
from pprint import pprint

# Add src to path
sys.path.append(str(Path('/content/drive/MyDrive/RAG/src').parent))

from src.config.config import Config
from src.document_ingestion.document_processor import DocumentProcessor
from src.vectorstore.vectorstore import VectorStore
from src.graph_builder.graph_builder_adv import GraphBuilder

In [ ]:
llm = Config.get_llm()
slm = Config.get_slm()
embedding = Config.get_embedding_model()
doc_processor = DocumentProcessor(embedding)
vector_store = VectorStore(embedding)

pdfs = '/content/drive/MyDrive/RAG/datasets'

document_processor = DocumentProcessor(embedding)
documents = document_processor.process(pdfs)

# Create vector store
vector_store.create_vectorstore(documents)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Chroma vector store created and persisted to /content/drive/MyDrive/RAG/chroma_db

In [ ]:
# Build graph
graph_builder = GraphBuilder(
    retriever=vector_store.get_retriever(),
    llm=llm,
    slm=slm
)
builder = graph_builder.build() # Assign the returned workflow to a variable

In [ ]:
%%time
import os
import math
import pandas as pd

# Ensure dataset is loaded if not already defined (in case previous cell was skipped)
if 'dataset' not in locals():
    # Assuming the path is correct as per accdd6c1
    dataset = pd.read_excel('/content/drive/MyDrive/RAG/datasets/datasets.xlsx', sheet_name="final")

answers = {}

for i, q in enumerate(dataset['question'].tolist()):
    # Skip NaN values in the question list
    if isinstance(q, float) and math.isnan(q):
        print(f"Skipping question at index {i} due to NaN value.")
        continue

    response = graph_builder.run(q)
    answers[i] = {} # Initialize the dictionary for the current query index
    answers[i]['query'] = response['question']
    answers[i]['answer'] = response['answer']
    answers[i]['retrieved_docs'] = [] # Initialize retrieved_docs as a list of dictionaries

    for doc in response['retrieved_docs']:
        answers[i]['retrieved_docs'].append({
            'content': doc.page_content,
            'doc_name': doc.metadata.get('title', os.path.basename(doc.metadata['source'])),
            'page': doc.metadata['page'],
            'page_label': doc.metadata['page_label'],
            'source': doc.metadata['source']
        })

Skipping question at index 170 due to NaN value.
CPU times: user 40.2 s, sys: 1.76 s, total: 42 s
Wall time: 27min 7s

In [ ]:
import pandas as pd

data_for_df = []
for idx, item in answers.items():
    base_row = {
        'index': idx,
        'query': item['query'],
        'answer': item['answer']
    }

    # Check if 'retrieved_docs' is a list and not empty
    if 'retrieved_docs' in item and isinstance(item['retrieved_docs'], list) and item['retrieved_docs']:
        for doc_info in item['retrieved_docs']:
            row = base_row.copy()
            row.update({
                'content': doc_info.get('content'),
                'doc_name': doc_info.get('doc_name'),
                'page': doc_info.get('page'),
                'page_label': doc_info.get('page_label'),
                'source': doc_info.get('source')
            })
            data_for_df.append(row)
    else:
        # Handle cases where retrieved_docs might be missing, not a list, or empty
        row = base_row.copy()
        row.update({
            'content': None,
            'doc_name': None,
            'page': None,
            'page_label': None,
            'source': None
        })
        data_for_df.append(row)

df_answers = pd.DataFrame(data_for_df)
display(df_answers.head())

,index,query,answer,content,doc_name,page,page_label,source
0,0,Which month is set aside each year in the UAE ...,"Okay, let's break this down step by step to an...",international reading performance benchmark fo...,Abu Dhabi.pdf,2,3,/content/drive/MyDrive/RAG/datasets/Abu Dhabi ...
1,0,Which month is set aside each year in the UAE ...,"Okay, let's break this down step by step to an...",international reading performance benchmark fo...,Abu Dhabi.pdf,2,3,/content/drive/MyDrive/RAG/datasets/Abu Dhabi ...
2,0,Which month is set aside each year in the UAE ...,"Okay, let's break this down step by step to an...",international reading performance benchmark fo...,Abu Dhabi.pdf,2,3,/content/drive/MyDrive/RAG/datasets/Abu Dhabi ...
3,0,Which month is set aside each year in the UAE ...,"Okay, let's break this down step by step to an...",international reading performance benchmark fo...,Abu Dhabi.pdf,2,3,/content/drive/MyDrive/RAG/datasets/Abu Dhabi ...
4,1,"How many public, private, and charter schools ...","Okay, let's break this down step by step to an...",There are 218 public schools with a student po...,Abu Dhabi.pdf,0,1,/content/drive/MyDrive/RAG/datasets/Abu Dhabi ...

In [ ]:
merged_df_by_qa = pd.merge(dataset, df_answers, left_on='question', right_on='query', how='left')
display(merged_df_by_qa.head())

,index_x,dataset_name,type,doc,question,answer_ref,passage_1_text,passage_1_page,passage_2_text,passage_2_page,Unnamed: 10,Unnamed: 11,index_y,query,answer,content,doc_name,page,page_label,source
0,1.0,dataset_1,synthetic,"""Z:\AI_Projects\RAG_R_and_D_Project\src\Abu Dh...",Which month is set aside each year in the UAE ...,March,Building on the Abu Dhabi Reads campaign launc...,3,"Every March, the UAE celebrates a month of rea...",6,NaN,NaN,0.0,Which month is set aside each year in the UAE ...,"Okay, let's break this down step by step to an...",international reading performance benchmark fo...,Abu Dhabi.pdf,2.0,3,/content/drive/MyDrive/RAG/datasets/Abu Dhabi ...
1,1.0,dataset_1,synthetic,"""Z:\AI_Projects\RAG_R_and_D_Project\src\Abu Dh...",Which month is set aside each year in the UAE ...,March,Building on the Abu Dhabi Reads campaign launc...,3,"Every March, the UAE celebrates a month of rea...",6,NaN,NaN,0.0,Which month is set aside each year in the UAE ...,"Okay, let's break this down step by step to an...",international reading performance benchmark fo...,Abu Dhabi.pdf,2.0,3,/content/drive/MyDrive/RAG/datasets/Abu Dhabi ...
2,1.0,dataset_1,synthetic,"""Z:\AI_Projects\RAG_R_and_D_Project\src\Abu Dh...",Which month is set aside each year in the UAE ...,March,Building on the Abu Dhabi Reads campaign launc...,3,"Every March, the UAE celebrates a month of rea...",6,NaN,NaN,0.0,Which month is set aside each year in the UAE ...,"Okay, let's break this down step by step to an...",international reading performance benchmark fo...,Abu Dhabi.pdf,2.0,3,/content/drive/MyDrive/RAG/datasets/Abu Dhabi ...
3,1.0,dataset_1,synthetic,"""Z:\AI_Projects\RAG_R_and_D_Project\src\Abu Dh...",Which month is set aside each year in the UAE ...,March,Building on the Abu Dhabi Reads campaign launc...,3,"Every March, the UAE celebrates a month of rea...",6,NaN,NaN,0.0,Which month is set aside each year in the UAE ...,"Okay, let's break this down step by step to an...",international reading performance benchmark fo...,Abu Dhabi.pdf,2.0,3,/content/drive/MyDrive/RAG/datasets/Abu Dhabi ...
4,2.0,dataset_2,synthetic,"""Z:\AI_Projects\RAG_R_and_D_Project\src\Abu Dh...","How many public, private, and charter schools ...","Abu Dhabi has 218 public schools, 203 private ...",There are 218 public schools with a student po...,1,"Exhibit 1: Demographics for Abu Dhabi Schools,...",2,NaN,NaN,1.0,"How many public, private, and charter schools ...","Okay, let's break this down step by step to an...",There are 218 public schools with a student po...,Abu Dhabi.pdf,0.0,1,/content/drive/MyDrive/RAG/datasets/Abu Dhabi ...

In [ ]:
merged_df_by_qa.to_csv('/content/drive/MyDrive/RAG/datasets/adv_rag_with_gemma3_result_20251223.csv', index=False)